### ISSUE TITLE
Seems like we ended up with dupe comments 

### ISSUE THREAD

**Issue by DragosDanielBoia** [microsoft/PullRequestQuantifier#128]
![image](https://user-images.githubusercontent.com/19934057/108579049-0e1ab380-72da-11eb-80a7-2276da9101b5.png)

Interesting this happened for 10-20 seconds, I guess is a delay in github, let's watch the behavior more and in case is not repro we can close this bug.

**Comment by goelhardik** [comment]
The issue is that GitHub UI only refreshes added comments automatically, not deleted comments. You have to refresh page to refresh the deleted comments.
