### ISSUE TITLE
Should be able to disable email notifications

### ISSUE THREAD

**Issue by tjnurmin** [microsoft/PullRequestQuantifier#168]
Couldn't find a way to suppress email notifications in

https://github.com/microsoft/PullRequestQuantifier/blob/main/docs/prquantifier-yaml.md

**Comment by goelhardik** [comment]
PRQuantifier does not actually send any email notifications. Those will be native GitHub notifications that you might be receiving when a comment happens on a PR, for example.

**Comment by tjnurmin** [comment]
Thanks. We dropped using PRQuantifier in favor of another labeler. It doesn't trigger those emails notifications.

**Comment by TheQueenIsDead** [comment]
> Thanks. We dropped using PRQuantifier in favor of another labeler. It doesn't trigger those email notifications.

@tjnurmin would you be able to share with me what solution you switched to? I'm currently looking for a decent labeller that does not require commenting (preferably freeware), thanks!

**Comment by tjnurmin** [comment]
> @tjnurmin would you be able to share with me what solution you switched to? I'm currently looking for a decent labeller that does not require commenting (preferably freeware), thanks!

Sure, we're using https://github.com/marketplace/pull-request-size and it works perfectly.
