### ISSUE TITLE
The "No Changes" label is not removed when the pull request size changes.

### ISSUE THREAD

**Issue by ouphi** [microsoft/PullRequestQuantifier#175]
The "No Changes" label is not removed when the pull request size changes.
The screenshot shows that the "No Changes" label is still present even if the PR is extra large.
<img width="1225" alt="Screenshot 2022-01-21 at 10 48 05" src="https://user-images.githubusercontent.com/17216799/150505754-98f91900-9317-4aea-afed-694fdaf4ec12.png">

**Comment by DragosDanielBoia** [comment]
Feel free to push a fix for this issue. Will review it.

**Comment by ouphi** [comment]
Hi @DragosDanielBoia and @goelhardik,
We merged PR #179 but the change did not get published.
I guess your api key expired, because I see that [build-and-publish-release](https://github.com/microsoft/PullRequestQuantifier/runs/6398930781?check_suite_focus=true) failed with this error `Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.`

**Comment by goelhardik** [comment]
@ouphi it's updated now and the nuget package is published.

**Comment by ouphi** [comment]
Thanks @goelhardik ! :)
